// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MenuItem struct {
	ID          string      `json:"id"`
	Type        string      `json:"type"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	URL         string      `json:"url"`
	DayOfWeek   string      `json:"dayOfWeek"`
	Restaurant  *Restaurant `json:"restaurant,omitempty"`
}

type Mutation struct {
}

type NewMenuItem struct {
	Type        string         `json:"type"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	URL         string         `json:"url"`
	DayOfWeek   string         `json:"dayOfWeek"`
	Restaurant  *NewRestaurant `json:"restaurant,omitempty"`
}

type NewRestaurant struct {
	Name string         `json:"name"`
	Date string         `json:"date"`
	Menu []*NewMenuItem `json:"menu"`
}

type Query struct {
}

type Restaurant struct {
	ID   string      `json:"id"`
	Name string      `json:"name"`
	Date string      `json:"date"`
	Menu []*MenuItem `json:"menu"`
}

type TypedMenuItem struct {
	Type string      `json:"type"`
	Menu []*MenuItem `json:"menu"`
}
